### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.stripe.android.PaymentSession.handlePaymentData(int, int, android.content.Intent)' on a null object reference

### ISSUE THREAD

**Issue by prasath95** [Nativeman21/StripeMobilePayment#2]
`2020-10-30 14:10:10.625 21101-21101/com.asgd.stripemobilepayment E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Error when saving credential.
        at com.firebase.ui.auth.viewmodel.smartlock.SmartLockHandler$1.onComplete(SmartLockHandler.java:99)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.google.android.gms.common.api.ApiException: 16: Cannot find an eligible account.
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
        at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
        at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
        at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
        at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.setResult(com.google.android.gms:play-services-base@@17.1.0:36)
        at com.google.android.gms.internal.auth-api.zzo.zzc(Unknown Source:4)
        at com.google.android.gms.internal.auth-api.zzv.dispatchTransaction(Unknown Source:9)
        at com.google.android.gms.internal.auth-api.zzd.onTransact(Unknown Source:12)
        at android.os.Binder.execTransact(Binder.java:731)
2020-10-30 14:10:13.034 21101-21101/com.asgd.stripemobilepayment E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.asgd.stripemobilepayment, PID: 21101
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {com.asgd.stripemobilepayment/com.example.stripemobilepayment.MainStripe}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.stripe.android.PaymentSession.handlePaymentData(int, int, android.content.Intent)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4349)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4391)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.stripe.android.PaymentSession.handlePaymentData(int, int, android.content.Intent)' on a null object reference
        at com.example.stripemobilepayment.MainStripe.onActivityResult(MainStripe.java:247)
        at android.app.Activity.dispatchActivityResult(Activity.java:7449)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4342)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4391) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6642) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

**Comment by Nativeman21** [comment]
You will need to use the LoginMethod every time for the ActivityResult. I altered in my project and maybe forgot to change back here to test faster

**Comment by prasath95** [comment]
> You will need to use the LoginMethod every time for the ActivityResult. I altered in my project and maybe forgot to change back here to test faster


Please can you push the latest code, it's a big help for me
